# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Fry-Lib-CDBI-Outline
version:      0.02
version_from: lib/Fry/Lib/CDBI/Outline.pm
installdirs:  site
requires:
    Class::Data::Global:           0.01
    Fry::Shell:                    0.08

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
